import { TYPE, IDS, ItemTypes } from "./constants";

export const fieldTypes = [
	{
		name: "Common",
		value: [
			{
				name: "label",
				title: "Label",
				type: "label",
				image: "label.png",
				id: IDS.createWidgets.field,
				serverType: "label",
				colSpan: 6,
			},
			{
				name: "button",
				type: "button",
				title: "Button",
				image: "button.png",
				id: IDS.createWidgets.field,
				serverType: "button",
				colSpan: 6,
			},
			{
				name: "separator",
				type: "separator",
				image: "seperator.png",
				id: IDS.createWidgets.field,
				serverType: "separator",
				colSpan: 6,
			},
			{
				name: "selection",
				title: "Selection",
				type: ItemTypes.ITEM,
				image: "dropdown-arrow.png",
				id: IDS.createWidgets.field,
				serverType: "string",
				isSelectionField: true,
				colSpan: 6,
			},
		],
	},
	{
		name: "Panels",
		value: [
			{
				name: "panel",
				type: ItemTypes.CONTAINER,
				items: [],
				image: "panel.png",
				id: IDS.createWidgets.panel,
				serverType: TYPE.panel,
				cols: 12,
				layout: "grid",
				colSpan: 12,
			},
			{
				name: "Tabs",
				type: TYPE.tabs,
				image: "panel_tabs.png",
				tab: true,
				items: [],
				id: IDS.createWidgets.tabs,
				serverType: TYPE.panel,
				isNew: true,
				colSpan: 12,
				title: "Tabs",
				current: null,
				layout: "grid",
			},
		],
	},
];

export const modelFields = [
	{
		name: "Fields",
		value: [
			{
				name: "string",
				type: ItemTypes.ITEM,
				title: "String",
				image: "string.png",
				id: IDS.createWidgets.field,
				isModelField: true,
				serverType: "string",
				colSpan: 6,
			},
			{
				name: "integer",
				type: ItemTypes.ITEM,
				title: "Integer",
				image: "integer.png",
				id: IDS.createWidgets.field,
				isModelField: true,
				serverType: "integer",
				colSpan: 6,
			},
			{
				name: "decimal",
				type: ItemTypes.ITEM,
				title: "Decimal",
				image: "decimal.png",
				id: IDS.createWidgets.field,
				isModelField: true,
				serverType: "decimal",
				colSpan: 6,
			},
			{
				name: "boolean",
				type: ItemTypes.ITEM,
				title: "Boolean",
				image: "boolean.png",
				id: IDS.createWidgets.field,
				isModelField: true,
				serverType: "boolean",
				colSpan: 6,
			},
			{
				name: "datetime",
				type: ItemTypes.ITEM,
				title: "Date time",
				image: "datetime.png",
				id: IDS.createWidgets.field,
				isModelField: true,
				serverType: "datetime",
				colSpan: 6,
			},
			{
				name: "date",
				type: ItemTypes.ITEM,
				title: "Date",
				image: "date.png",
				id: IDS.createWidgets.field,
				isModelField: true,
				serverType: "date",
				colSpan: 6,
			},
			{
				name: "time",
				type: ItemTypes.ITEM,
				title: "Time",
				image: "time.png",
				id: IDS.createWidgets.field,
				isModelField: true,
				serverType: "time",
				colSpan: 6,
			},
		],
	},
	{
		name: "Relational fields",
		value: [
			{
				name: "manyToOne",
				type: ItemTypes.ITEM,
				title: "Many to one",
				image: "many-to-one.png",
				id: IDS.createWidgets.field,
				isModelField: true,
				serverType: "many-to-one",
				colSpan: 6,
			},
			{
				name: "oneToMany",
				type: ItemTypes.ITEM,
				title: "One to many",
				image: "one-to-many.png",
				id: IDS.createWidgets.field,
				isModelField: true,
				serverType: "one-to-many",
				colSpan: 6,
			},
			{
				name: "manyToMany",
				type: ItemTypes.ITEM,
				title: "Many to many",
				image: "many-to-many.png",
				id: IDS.createWidgets.field,
				isModelField: true,
				serverType: "many-to-many",
				colSpan: 6,
			},
		],
	},
];
