= Modification d'instance de processus
:toc-title:
:page-pagination:
:experimental:

== Description de la fonctionnalité


Cette fonctionnalité permet aux utilisateurs de modifier manuellement l'état d'une instance de processus en cours d'exécution.

Les modifications possibles sont :

    Démarrer avant une activité.
    Démarrer après une activité.
    Démarrer une transition.
    Annuler une instance d'activité.
    Annuler une instance de transition.
    Annuler toutes les instances d'activité pour une activité.
    Soumettre des variables de processus avec pour chaque modification.


== Description du flux de travail


Cette fonctionnalité est accessible via le menu : Application/Composants BPM/Suivi technique/Modification d'instance de processus.

Les informations suivantes sont nécessaires pour utiliser cette fonctionnalité :

1. ID de l'instance de processus concernée par la modification.
2. IDs de toutes les activités impliquées dans la modification.

La fonctionnalité est basée sur un script YAML qui contient les modifications à appliquer pour chaque instance de processus.

La syntaxe est la suivante :

[source,yaml]
----
migration:
  - instance:
      name:
        - "process-instance-1-id"
        - "process-instance-2-id"
      operations:
        - cancelAll("activity-1-id")
        - startBefore("activity-2-id")
  - instance:
      name:
        - "process-instance-3-id"
        - "process-instance-4-id"
      operations:
        - cancelAll("activity-3-id")
        - startAfter("activity-4-id","var-name","var-value")

----
=== Mapping des opérations
Voici une correspondance entre les modifications possibles et les mots-clés qui peuvent les déclencher :

    Démarrer avant une activité : startBefore("activity-id")
    Démarrer avant une activité et soumettre une variable de processus : startBefore("activity-id", "name", "value")
    Démarrer après une activité : startAfter("activity-id")
    Démarrer après une activité et soumettre une variable de processus : startAfter("activity-id", "name", "value")
    Démarrer une transition : startTransition("transition-id")
    Démarrer une transition et soumettre une variable de processus : startTransition("transition-id", "name", "value")
    Annuler toutes les instances d'activité pour une activité : cancelAll("activity-id")
    Annuler une instance d'activité : cancelActivityInstance("activity-instance-id")
    Annuler une instance de transition : cancelTransition("transition-instance-id")

== Script
Les utilisateurs ont la possibilité de saisir manuellement le script dans le champ dédié ou de télécharger un fichier contenant le script. Par ailleurs, le système offre aux utilisateurs la faculté de télécharger le script sous forme de fichier en vue de références futures ou d'une utilisation ultérieure.
